//申明数据
var data = [{
		oneF: [{
			links: ['女装', '男装', '内衣', '女鞋', '箱包', '珠宝配件', '钟表眼镜', '运动户外', ],
		}, {
			Title: [{
				log: '&#xe613;',
				title: '服装城',
			}, {
				log: '&#xe60e;',
				title: '运动馆',
			}, {
				log: '&#xe620;',
				title: '皮具箱包',
			}, {
				log: '&#xe617;',
				title: '钟表珠宝',
			}, ],
			bigImg: ['img/1floor/1.jpg', 'img/1floor/8.jpg', ],
			Img: [{
				sImg: 'img/1floor/2.jpg',
			}, {
				sImg: 'img/1floor/3.jpg',
			}, {
				sImg: 'img/1floor/4.jpg',
			}, {
				sImg: 'img/1floor/5.jpg',
			}, {
				sImg: 'img/1floor/6.jpg',
			}, {
				sImg: 'img/1floor/7.jpg',
			}, ],

			col2: [{
				sImg: 'img/1floor/9.jpg',
			}, {
				sImg: 'img/1floor/10.jpg',
			}, {
				sImg: 'img/1floor/11.jpg',
			}, {
				sImg: 'img/1floor/12.jpg',
			}, ],
			col3: [{
				sImg: 'img/1floor/13.jpg',
			}, {
				sImg: 'img/1floor/14.jpg',
			}, {
				sImg: 'img/1floor/15.jpg',
			}, ],
		}, ],
	}, {
		twoF: [{
			links: ['iphone6s', '华为荣耀7', '小米note3', '三星note5', '魅族max5', '大神note3', '努比亚', '华为p8', ],
		}, {
			Title: [{
				log: '&#xe613;',
				title: '热卖手机',
			}, {
				log: '&#xe60e;',
				title: '手机配件',
			}, {
				log: '&#xe620;',
				title: '智能手环',
			}, {
				log: '&#xe617;',
				title: '营业厅',
			}, ],
			bigImg: ['img/2floor/1.jpg', 'img/2floor/8.jpg', ],
			Img: [{
				sImg: 'img/2floor/2.jpg',
			}, {
				sImg: 'img/2floor/3.jpg',
			}, {
				sImg: 'img/2floor/4.jpg',
			}, {
				sImg: 'img/2floor/5.jpg',
			}, {
				sImg: 'img/2floor/6.jpg',
			}, {
				sImg: 'img/2floor/7.jpg',
			}, ],

			col2: [{
				sImg: 'img/2floor/9.jpg',
			}, {
				sImg: 'img/2floor/10.jpg',
			}, {
				sImg: 'img/2floor/11.jpg',
			}, {
				sImg: 'img/2floor/12.jpg',
			}, ],
			col3: [{
				sImg: 'img/2floor/13.jpg',
			}, {
				sImg: 'img/2floor/14.jpg',
			}, {
				sImg: 'img/2floor/15.jpg',
			}, ],
		}, ],
	}, {
		threeF: [{
			links: ['洗衣液', '四件套', '茶具', '卷纸', '清洁用品', '被子', '纸抽', '安全避孕', ],
		}, {
			Title: [{
				log: '&#xe613;',
				title: '超市频道',
			}, {
				log: '&#xe60e;',
				title: '天天低价',
			}, ],
			bigImg: ['img/3floor/1.jpg', 'img/3floor/8.jpg', ],
			Img: [{
				sImg: 'img/3floor/2.gif',
			}, {
				sImg: 'img/3floor/3.gif',
			}, {
				sImg: 'img/3floor/4.gif',
			}, {
				sImg: 'img/3floor/5.gif',
			}, {
				sImg: 'img/3floor/6.gif',
			}, {
				sImg: 'img/3floor/7.gif',
			}, ],

			col2: [{
				sImg: 'img/3floor/9.jpg',
			}, {
				sImg: 'img/3floor/10.jpg',
			}, {
				sImg: 'img/3floor/11.jpg',
			}, {
				sImg: 'img/3floor/12.jpg',
			}, ],
			col3: [{
				sImg: 'img/3floor/13.jpg',
			}, {
				sImg: 'img/3floor/14.jpg',
			}, {
				sImg: 'img/3floor/15.jpg',
			}, ],
		}, ],
	}, {
		fourF: [{
			links: ['月饼', '牛奶乳品', '饼干糕点', '食用油', '白酒', '坚果', '进口休闲', '大米', ],
		}, {
			Title: [{
				log: '&#xe613;',
				title: '超市频道',
			}, {
				log: '&#xe60e;',
				title: '生鲜蔬果',
			}, {
				log: '&#xe620;',
				title: '中华特色',
			}, {
				log: '&#xe617;',
				title: '天天低价',
			}, ],
			bigImg: ['img/4floor/1.jpg', 'img/4floor/8.jpg', ],
			Img: [{
				sImg: 'img/4floor/2.gif',
			}, {
				sImg: 'img/4floor/3.gif',
			}, {
				sImg: 'img/4floor/4.gif',
			}, {
				sImg: 'img/4floor/5.gif',
			}, {
				sImg: 'img/4floor/6.gif',
			}, {
				sImg: 'img/4floor/7.gif',
			}, ],

			col2: [{
				sImg: 'img/4floor/9.jpg',
			}, {
				sImg: 'img/4floor/10.jpg',
			}, {
				sImg: 'img/4floor/11.jpg',
			}, {
				sImg: 'img/4floor/12.jpg',
			}, ],
			col3: [{
				sImg: 'img/4floor/13.jpg',
			}, {
				sImg: 'img/4floor/14.jpg',
			}, {
				sImg: 'img/4floor/15.jpg',
			}, ],
		}, ],
	}, {
		fiveF: [{
			links: ['奶粉', '童鞋', '婴儿洗衣液', '安全座椅', '户外玩具', '婴童套装', ],
		}, {
			Title: [{
				log: '&#xe613;',
				title: '红孩子母婴',
			}, ],
			bigImg: ['img/5floor/1.jpg', 'img/5floor/8.jpg', ],
			Img: [{
				sImg: 'img/5floor/2.jpg',
			}, {
				sImg: 'img/5floor/3.jpg',
			}, {
				sImg: 'img/5floor/4.jpg',
			}, {
				sImg: 'img/5floor/5.jpg',
			}, {
				sImg: 'img/5floor/6.jpg',
			}, {
				sImg: 'img/5floor/7.jpg',
			}, ],
			col2: [{
				sImg: 'img/5floor/9.jpg',
			}, {
				sImg: 'img/5floor/10.jpg',
			}, {
				sImg: 'img/5floor/11.jpg',
			}, {
				sImg: 'img/5floor/12.jpg',
			}, ],
			col3: [{
				sImg: 'img/5floor/13.jpg',
			}, {
				sImg: 'img/5floor/14.jpg',
			}, {
				sImg: 'img/5floor/15.jpg',
			}, ],
		}, ],
	}, {
		sixF: [{
			links: ['面膜','洗面奶','水乳','彩妆','洗发水','手霜','牙膏','卫生巾',],
		}, {
			Title: [{
				log: '&#xe613;',
				title: '美妆个护',
			}, ],
			bigImg: ['img/6floor/1.jpg', 'img/6floor/8.jpg', ],
			Img: [{
				sImg: 'img/6floor/2.jpg',
			}, {
				sImg: 'img/6floor/3.jpg',
			}, {
				sImg: 'img/6floor/4.jpg',
			}, {
				sImg: 'img/6floor/5.jpg',
			}, {
				sImg: 'img/6floor/6.jpg',
			}, {
				sImg: 'img/6floor/7.gif',
			}, ],

			col2: [{
				sImg: 'img/6floor/9.jpg',
			}, {
				sImg: 'img/6floor/10.jpg',
			}, {
				sImg: 'img/6floor/11.jpg',
			}, {
				sImg: 'img/6floor/12.jpg',
			}, ],
			col3: [{
				sImg: 'img/6floor/13.jpg',
			}, {
				sImg: 'img/6floor/14.jpg',
			}, {
				sImg: 'img/6floor/15.jpg',
			}, ],
		}, ],
	}, {
		sevenF: [{
			links: ['iPad','笔记本','台式机','DIY','单反','微单','佳能','尼康',],
		}, {
			Title: [{
				log: '&#xe613;',
				title: '服装城',
			}, {
				log: '&#xe60e;',
				title: '运动馆',
			}, {
				log: '&#xe620;',
				title: '皮具箱包',
			}, {
				log: '&#xe617;',
				title: '钟表珠宝',
			}, ],
			bigImg: ['img/7floor/1.jpg', 'img/7floor/8.jpg', ],
			Img: [{
				sImg: 'img/7floor/2.jpg',
			}, {
				sImg: 'img/7floor/3.jpg',
			}, {
				sImg: 'img/7floor/4.jpg',
			}, {
				sImg: 'img/7floor/5.jpg',
			}, {
				sImg: 'img/7floor/6.jpg',
			}, {
				sImg: 'img/7floor/7.jpg',
			}, ],

			col2: [{
				sImg: 'img/7floor/9.jpg',
			}, {
				sImg: 'img/7floor/10.jpg',
			}, {
				sImg: 'img/7floor/11.jpg',
			}, {
				sImg: 'img/7floor/12.jpg',
			}, ],
			col3: [{
				sImg: 'img/7floor/13.jpg',
			}, {
				sImg: 'img/7floor/14.jpg',
			}, {
				sImg: 'img/7floor/15.jpg',
			}, ],
		}, ],
	}, {
		eightF: [{
			links: ['生活电器','净水器','个护健康','冰箱','洗衣机','电视','空调','热水器',],
		}, {
			Title: [{
				log: '&#xe613;',
				title: '电器城',
			}, ],
			bigImg: ['img/8floor/1.jpg', 'img/8floor/8.jpg', ],
			Img: [{
				sImg: 'img/8floor/2.jpg',
			}, {
				sImg: 'img/8floor/3.jpg',
			}, {
				sImg: 'img/8floor/4.jpg',
			}, {
				sImg: 'img/8floor/5.jpg',
			}, {
				sImg: 'img/8floor/6.gif',
			}, {
				sImg: 'img/8floor/7.jpg',
			}, ],

			col2: [{
				sImg: 'img/8floor/9.jpg',
			}, {
				sImg: 'img/8floor/10.jpg',
			}, {
				sImg: 'img/8floor/11.jpg',
			}, {
				sImg: 'img/8floor/12.jpg',
			}, ],
			col3: [{
				sImg: 'img/8floor/13.jpg',
			}, {
				sImg: 'img/8floor/14.jpg',
			}, {
				sImg: 'img/8floor/15.jpg',
			}, ],
		}, ],
	}, {
		nineF: [{
			links: ['床垫','置物架','花洒','马桶','客厅灯','插座','龙头',],
		}, {
			Title: [{
				log: '&#xe613;',
				title: '家装馆',
			}, ],
			bigImg: ['img/9floor/1.jpg', 'img/9floor/8.jpg', ],
			Img: [{
				sImg: 'img/9floor/2.jpg',
			}, {
				sImg: 'img/9floor/3.jpg',
			}, {
				sImg: 'img/9floor/4.jpg',
			}, {
				sImg: 'img/9floor/5.jpg',
			}, {
				sImg: 'img/9floor/6.jpg',
			}, {
				sImg: 'img/9floor/7.jpg',
			}, ],

			col2: [{
				sImg: 'img/9floor/9.jpg',
			}, {
				sImg: 'img/9floor/10.jpg',
			}, {
				sImg: 'img/9floor/11.jpg',
			}, {
				sImg: 'img/9floor/12.jpg',
			}, ],
			col3: [{
				sImg: 'img/9floor/13.jpg',
			}, {
				sImg: 'img/9floor/14.jpg',
			}, {
				sImg: 'img/9floor/15.jpg',
			}, ],
		}, ],
	}, {
		tenF: [{
			links: ['孕产育儿','互联网时代','矛盾文学','电子书','教育考试','绘本',],
		}, {
			Title: [{
				log: '&#xe613;',
				title: '服装城',
			}, {
				log: '&#xe60e;',
				title: '运动馆',
			}, {
				log: '&#xe620;',
				title: '皮具箱包',
			}, {
				log: '&#xe617;',
				title: '钟表珠宝',
			}, ],
			bigImg: ['img/10floor/1.jpg', 'img/10floor/8.jpg', ],
			Img: [{
				sImg: 'img/10floor/2.gif',
			}, {
				sImg: 'img/10floor/3.gif',
			}, {
				sImg: 'img/10floor/4.gif',
			}, {
				sImg: 'img/10floor/5.gif',
			}, {
				sImg: 'img/10floor/6.gif',
			}, {
				sImg: 'img/10floor/7.jpg',
			}, ],

			col2: [{
				sImg: 'img/10floor/9.jpg',
			}, {
				sImg: 'img/10floor/10.jpg',
			}, {
				sImg: 'img/10floor/11.jpg',
			}, {
				sImg: 'img/10floor/12.jpg',
			}, ],
			col4: [{
				sImg: 'img/10floor/13.jpg',
				name: '秘密花园：一本探索奇境的手绘涂色书：手绘唯美经典涂',
				price: '24',
			}, {
				sImg: 'img/10floor/14.jpg',
				name: '花千骨纪念典藏版上下共2册 【 随书赠送全套4张唯美剧照】赵丽颖、霍建华、蒋欣等倾情演绎 全新番外 仙侠言情小说',
				price: '21',
			}, {
				sImg: 'img/10floor/15.jpg',
				name: '郑玉巧育儿经：胎儿卷+婴儿卷+幼儿卷（全3册）',
				price: '94',
			}, {
				sImg: 'img/10floor/16.jpg',
				name: '3-6岁斯凯瑞金色童书·第1辑全4册轱辘轱辘转、忙忙碌碌镇、会讲故事的单词书、斯凯瑞最受欢迎的故事',
				price: '28',
			}, ],
		}, ],
	}, {
		mainCol: [{
			sellGoodsUp: [{
				id: 1,
				face: 'img/s1/1.jpg',
				name: '七格格OTHERMIX2018秋新款 网纱拼接弹力修身长袖一字领T恤',
				price: '345',
			}, {
				id: 2,
				face: 'img/s1/2.jpg',
				name: '幸福时光2018秋冬新款男士套装 卫衣套装卫衣男店主风 男士运动套装 开衫套装 XXL 灰色',
				price: '134',
			}, {
				id: 3,
				face: 'img/s1/3.jpg',
				name: '【5装装】俞兆林男袜 隐形船袜短袜 防臭浅口袜低帮棉袜 迷彩 均码',
				price: '56',
			}, {
				id: 4,
				face: 'img/s1/4.jpg',
				name: '2018新款时尚女鞋深口休闲鞋细带鞋花色运动鞋YD5BB4188 粉色 37码',
				price: '234',
			}, {
				id: 5,
				face: 'img/s1/5.jpg',
				name: '花花公子 时尚休闲皮带 男士腰带 板扣裤腰带PDA0586-4B 黑色 120cm',
				price: '340',
			}, ],
		}, {
			sellGoodsDown: [{
				face: 'img/s1/6.jpg',
				name: '罗西尼唯美花样璀璨石英女表',
				price: '343',
			}, {
				face: 'img/s1/7.jpg',
				name: '百年宝诚 S990足银手镯女圆手环镂空银饰甜美时尚瑞丽花丝银镯子 花瓣款',
				price: '855',
			}, {
				face: 'img/s1/8.jpg',
				name: '鸿星尔克男运动鞋 跑步鞋 男常规跑鞋FD11114203414 青铜灰/金 42码',
				price: '433',
			}, {
				face: 'img/s1/9.jpg',
				name: '探路者秋冬男式保暖厚实连帽套头卫衣TAUC91565 TAUC91565-G15X深花灰 XL',
				price: '325',
			}, {
				face: 'img/s1/10.jpg',
				name: '战地吉普男士长袖T恤 2018秋装针织T恤 圆领青年打底衫 天蓝色 L',
				price: '234',
			}, ],
		}, {
			similar: '找相似',
		}, ],
	},

];
//将数据转为字符串
var str = JSON.stringify(data);
//将数据存到localStorage
localStorage.SNFloorData = str;

//